# Generated by Django 3.2.25 on 2025-05-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuse',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
