# Generated by Django 3.2.25 on 2025-05-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_propuse_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuse',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propuse',
            name='return_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propuse',
            name='return_status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='borrowed', max_length=10),
        ),
    ]
